version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  x86-64-unknown-linux-nightly:
    docker:
      - image: ponylang/ponyup-ci-nightly-builder:latest
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-nightly.bash ${CLOUDSMITH_API_KEY}
      - zulip/status:
          fail_only: true

  shellcheck-init-script:
    docker:
      - image: ponylang/shared-docker-ci-shellcheck:20191008
    steps:
      - checkout
      - run: shellcheck ponyup-init.sh
      - zulip/status:
          fail_only: true

  vs-ponyc-release:
    docker:
      - image: ponylang/ponyup-ci-ponyc-release:latest
    steps:
      - checkout
      - run: make test ssl=0.9.0
      - run: .ci-scripts/test-bootstrap.sh
      - zulip/status:
          fail_only: true

  vs-ponyc-master:
    docker:
      - image: ponylang/ponyup-ci-ponyc-latest:latest
    steps:
      - checkout
      - run: make test ssl=0.9.0
      - zulip/status:
          fail_only: true

  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify
      - zulip/status:
          fail_only: true

  update-nightly-builder:
    docker:
      - image: ponylang/shared-docker-ci-docker-builder:20190808
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
      - run: bash .ci-dockerfiles/nightly-builder/build-and-push.bash
      - zulip/status:
          fail_only: true

  update-ponyc-latest:
    docker:
      - image: ponylang/shared-docker-ci-docker-builder:20190808
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
      - run: bash .ci-dockerfiles/ponyc-latest/build-and-push.bash
      - zulip/status:
          fail_only: true

  update-ponyc-release:
    docker:
      - image: ponylang/shared-docker-ci-docker-builder:20190808
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
      - run: bash .ci-dockerfiles/ponyc-release/build-and-push.bash
      - zulip/status:
          fail_only: true

workflows:
  version: 2.1

  # PR acceptance tests, shouldn't run on `master` branche
  pr-acceptance-tests:
    jobs:
      - shellcheck-init-script:
          context: org-global
          filters:
            branches:
              ignore:
                - master
      - verify-changelog:
          context: org-global
          filters:
            branches:
              ignore:
                - master
      - vs-ponyc-release:
          context: org-global
          filters:
            branches:
              ignore:
                - master

  daily-check-for-breakage:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master:
          context: org-global

  create-and-upload-nightly-release:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - x86-64-unknown-linux-nightly:
          context: org-global

  daily-image-updates:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - update-nightly-builder:
          context: org-global
      - update-ponyc-latest:
          context: org-global
      - update-ponyc-release:
          context: org-global
