name: CI image updates

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update-x86-64-unknown-linux-builder:
    name: Update x86-64-unknown-linux-builder image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-dockerfiles/x86-64-unknown-linux-builder/build-and-push.bash

  update-ponyc-release:
    name: Update ponyup ponyc:release image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-dockerfiles/ponyc-release/build-and-push.bash
