name: Release Notes Bot

on:
  push:
    branches:
      - master
    paths-ignore:
      - .release-notes/next-release.md

jobs:
  release-notes-bot:
    runs-on: ubuntu-latest
    name: Update release notes
    steps:
      - name: Update
        uses: ponylang/release-notes-bot-action@0.1.0
        with:
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          API_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}
